name: Build, Stop, Deploy, and Start Python app on Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Zip artifact for deployment
        run: |
          mkdir -p release
          # --- ИЗМЕНЕНИЕ ЗДЕСЬ ---
          cp app.py requirements.txt ./release/
          cp -r venv/lib/python3.11/site-packages/* ./release/
          cd release
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_887A53245E9B4CC5A9DA0D70CD8FE744 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3E2AB6118369497F8F3580D1100DC99B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7683B639F799416E85632E1D3075235C }}

      - name: Disable Build on Deploy
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp config appsettings set --name 'agka-tg-bot' --resource-group 'agka-tg-bot' --settings SCM_DO_BUILD_DURING_DEPLOYMENT=false

      - name: Stop Azure Web App
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp stop --name 'agka-tg-bot' --resource-group 'agka-tg-bot'

      - name: Wait for 60 seconds
        run: sleep 60

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'agka-tg-bot'
          slot-name: 'Production'
          package: release.zip

      - name: Start Azure Web App
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp start --name 'agka-tg-bot' --resource-group 'agka-tg-bot'