# Этот workflow просто отправляет исходный код в Azure
name: Deploy Python app to Azure Web App
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Необходимо для входа в Azure
    
    steps:
      # 1. Скачиваем ваш код из репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Входим в Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          # ВАШИ СЕКРЕТЫ ДОЛЖНЫ БЫТЬ ТУТ, GitHub подставит их сам
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_887A53245E9B4CC5A9DA0D70CD8FE744 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3E2AB6118369497F8F3580D1100DC99B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7683B639F799416E85632E1D3075235C }}

      # 3. Отправляем код "как есть" в Azure
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'agka-tg-bot'
          slot-name: 'Production'
